name: Create UPM Branch for version Tags
on: 
  create:
    branches:
      - master
    tags:
      - v[0-9].[0-9].[0-9]*

jobs:
  build:
    name: Branch
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Branch
        if: github.event.ref_type == 'tag'
        run: | 
          echo 'Creating Branch ${{env.BRANCH_NAME}} for Tag ${{env.TAG_NAME}}'
          git subtree split -P "$PKG_ROOT" -b env.BRANCH_NAME
          git push -u origin env.BRANCH_NAME
    env:
      PKG_ROOT: testpackagefolder
      TAG_NAME: ${{github.event.ref}}
      BRANCH_NAME: upm-${{github.event.ref}}