name: Create branch for version tags
on: 
  create:
    branches:
      - master
    tags:
      - v[0-9].[0-9].[0-9]*

jobs:
  build:
    name: Branch
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      if: github.event.ref_type == 'tag'
      - name: Create Branch
      run: echo 'Creating Branch ${{env.BRANCH_NAME}} Tag ${{env.TAG_NAME}}'
    env:
      TAG_NAME: ${{github.event.ref}}
      BRANCH_NAME: upm-${{github.event.ref}}